version: "3"

services:
  blog-vue:
    image: blog-vue:latest
    ports: 
      - "80:80"
    restart: always
    depends_on: 
      - blog-back-end
  blog-back-end:
    image: caoyuqian/blog-for-docker:1.0.0
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
      - redis
      - rabbitmq
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: lumia
    volumes:
      - $PWD/conf:/etc/mysql/conf.d
      - $PWD/logs:/logs
      - $PWD/data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: my_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis/data:/data
      - $PWD/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
  rabbitmq:
    image: rabbitmq:3.7.7-management
    container_name: my_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=lumia
      - RABBITMQ_DEFAULT_PASS=lumia
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"