server:
  http:
    port: 8080
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  datasource:
    name: blog
    url: jdbc:postgresql://106.12.97.86:5432/blog
    username: postgres
    password: lumiaqian
    driver-class-name: org.postgresql.Driver
  redis:
    host: 106.12.97.86
    port: 6379
    password: lumiaqian
    pool:
      max-idle: 5000
      max-active: 5000
      min-idle: 50
      testOnBorrow: true
      max-wait: 200
    timeout: 5000
    database: 0


mybatis:
  mapper-locations: classpath:mapper/*.xml

appKey:
  ak: 4sl4FWeMQ5Kv8GzCjxSYk8ih1LD4bMUL
  coor: bd09ll