server:
  http:
    port: 8080
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 106.12.97.86:9300
  datasource:
    name: blog
    #url: jdbc:postgresql://106.12.97.86:5432/blog 39.108.115.109
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: lumia
    #driver-class-name: org.postgresql.Driver
    driver-class-name: com.mysql.jdbc.Driver
  redis:
#    host: 106.12.97.86
    host: 127.0.0.1
    port: 6379
#    password: lumiaqian
    pool:
      max-idle: 5000
      max-active: 5000
      min-idle: 50
      testOnBorrow: true
      max-wait: 200
    timeout: 5000
    database: 0
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: lumia
#    password: lumia
#    # 消息发送到交换器确认机制,是否确认回调
#    publisher-confirms: true
#    publisher-returns: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
appKey:
  ak: 4sl4FWeMQ5Kv8GzCjxSYk8ih1LD4bMUL
  coor: bd09ll

prop:
  upload-folder: ../posts/

qiniu:
  accessKey: cH8YmWY4vG4JRONomuwhKgUdxVq9u4Aj4DKhP78e
  secretKey: WE1kYmpa8UA2j12NsGh7OnJwUoaACEx3i2KaidXO
  bucket: lumiaqian
  path: http://pj9aecdab.bkt.clouddn.com/

user:
  userId: 17679123317