spring:
  profiles:
    active: prod

mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
appKey:
  ak: 4sl4FWeMQ5Kv8GzCjxSYk8ih1LD4bMUL
  coor: bd09ll

prop:
  upload-folder: ../posts/
  url: https://images.caoyuqian.cn/api/upload/file

qiniu:
  accessKey: cH8YmWY4vG4JRONomuwhKgUdxVq9u4Aj4DKhP78e
  secretKey: WE1kYmpa8UA2j12NsGh7OnJwUoaACEx3i2KaidXO
  bucket: lumiaqian
  path: http://image.caoyuqian.cn/

user:
  userId: 17679123317